version: "3.8"

services:

  db:
    container_name: Digital_logistics_keycloack
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rajabarca
      POSTGRES_DB: DigitalLogistics_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - jenkins-net

  pgadmin:
    container_name: pgadmin-DigitalLogistics_keycloack
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: yassine@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - jenkins-net

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins_test_keycloack
    privileged: true
    user: root
    restart: always
    ports:
      - "8083:8080"
      - "50001:50001"
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src:/var/jenkins_data/workspace/src
    networks:
      - jenkins-net

  sonarqube:
    image: sonarqube:community
<<<<<<< Updated upstream
    container_name: sonarqubee
    restart: always
=======
    container_name: sonarqube_keycloack
>>>>>>> Stashed changes
    ports:
      - "9001:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - jenkins-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak-DigitalLogistics
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_DATABASE: DigitalLogistics_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: rajabarca

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - jenkins-net

volumes:
  db_data:
  jenkins_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

networks:
  jenkins-net:
    driver: bridge
